### PR TITLE
Added Attachment upload to ticket creation and comments

### PR DESCRIPTION
**Pull request by tmcdon89**
Files may be uploaded to tickets at the creation screen or in comments.
Attached files are displayed in the ticket information area within an
opened ticket. Files can be downloaded by clicking on the name within
the ticket information area.
Files are stored within the storage_path()/app/attachments/user/
folders

Please let me know any comments/suggestions

### CODE REVIEW

**Comment by thekordy** [comment]
I think the migration misses the filepath column

**Comment by tmcdon89** [comment]
Whoops looks like you're right! I added the test migration instead of the final. I'll get that changed out once I'm near a computer.

**Comment by fishmad** [comment]
This is good tmcdon89, I noted that private comments can also upload images but the image is not made private.. not sure if this may pose any issue it was just an observation

At this stage there is no ability to delete or edit replies through admin interface Im concerned that an admin or agent may accidentally post the wrong reply or spelling issue and I cannot be changed once its posted (applies to both private and general responses).

Just wonder what your thoughts are separating out the private response section (say beside the main response) as oppose to being in-line so one does not forget to accidentally tick the private check box.

Good job by the way.

**Comment by tmcdon89** [comment]
I agree with you on your points fishmad. My personal take on the private and public comments form would be to do something along the lines of what github has with the "Write" and "Preview" sections of their comments. So one side would be public, the other private. Didn't have a chance to tackle that yet so for the time being I implemented as a checkbox. 

As for the submitted comments display I think that if they were to be separated, they would still need a way to view them side by side for timeline purposes. That way private comments that reference public comments from the customer or another agent will make sense in perspective. 

I definitely think that comments need to be editable for the reasons stated, and that shouldn't be overly complicated to add. One thing that I've used in a ticketing system previously was an additional option to send an update to the client. So you could have public comments that weren't emailed out, incase you wanted to make changes etc... but if the user happened to log in looking for an update they would see the comment.

I really didn't even think about privately added attachments being private from the customer like comments. Thats only logical and should probably be implemented. That should be an extra column in the table and a small change to the view though.

I appreciate all the feedback. I find this project very useful for my companies needs so I tend to be a little biased on what I'm contributing first and how it gets displayed/implemented. The feedback helps keep it in perspective for how others might be using it.

**Comment by thekordy** [comment]
@tmcdon89  I am sorry I have not noticed that you submitted the new migration, I do not know why I have not got any notification?

**Pull request merged**
