### PR TITLE
Widgetized

### PR DESCRIPTION
**Pull request by imanghafoori1**
Using laravel-widgetize helps you in caching with less code and simpler logic in your controllers.
It moves the caching logic from controllers into another library.

### CODE REVIEW

**Comment by imanghafoori1** [comment]
@balping Something like this.
I see many other parts of the app which needs the same thing.

**Comment by balping** [comment]
You keep pushing, please tell meif you think the pr is ready

**Comment by imanghafoori1** [comment]
@balping 
Up until now the concept somewhat clear.
I have downloaded and tested my own fork.

I wait for your approval.

**Comment by balping** [comment]
Ok, I'll have a look. Thanks.

UPDATE: just to let you know, this PR is not forgotten, I just haven't had time to properly review it, but I will when I got some time.

**Pull request closed without merging**
