### PR TITLE
Add ability to complete and reopen tickets.

### PR DESCRIPTION
**Pull request by FusionDesign**
* Fixes Bootstrap Modal problem (modal-lg added)
* Adds Completed and Active tickets. Abilities that comes with that as well. See Edit Ticket.
* Updates routing to fluent
* Updates TicketController
* Fixes textbox positioning with long category names or status names.

### CODE REVIEW

**Comment by FusionDesign** [comment]
I know I can push directly, but I'm a Github newbie so I have no idea what I'm doing :8ball: 

Teach me your ways with tags and milestones!

**Comment by FusionDesign** [comment]
I'm fixing a couple of bugs. Just a moment.

**Comment by FusionDesign** [comment]
Adds Complete status in blue if ticket is complete. I found it silly to have to make every make a Complete status and then have to look up the ID of it and try to position it at the bottom of the list. Seemed hackish.

Also fixes permissions for standard users.

**Comment by FusionDesign** [comment]
Adds email notify integration to Complete status. Does not email when ticket is re-opened nor does it trigger a status change when a ticket is re-opened. 

I didn't think this was necessary because the first thing you'd do after re-opening a ticket is change the status. If you'd like, I can refactor further.

**Comment by FusionDesign** [comment]
Verified email comms with Mandrill App

**Comment by thekordy** [comment]
Good Job :+1:   ... I will test it tonight and get back to you with results

**Comment by FusionDesign** [comment]
Thank you :)

**Comment by thekordy** [comment]
After testing it, no Errors :+1:  ... just some minor comments .. also I would recommend (from the usability point of view) that the completed stage is linked to a closing status, so when the user/agent/admin click completed it will change the ticket status as well. Doing that will make no need to enter the edit mode in order to close the ticket, otherwise, entering the edit mode will be needed because the agent will need to change the status as well.

**Comment by thekordy** [comment]
Of course then we will need to add additional config parameter for the closing status id :)

**Comment by thekordy** [comment]
Is there any way to resubmit this PR to the v0.1.0 branch instead of pushing it directly to the master?

**Comment by FusionDesign** [comment]
Yup! Let me revise tonight and adjust to 0.1.0

**Comment by FusionDesign** [comment]
Also, my build system automatically re-formats code on save. Do we want to adhere to PSR-2?

**Comment by thekordy** [comment]
We should adhere to PSR-2 as long as we can, and please ignore my comment on if statements, I didn't know it is a PSR-2 format.

**Comment by FusionDesign** [comment]
Believe me, I hated it too. They also use spaces. :shutter: -- I guess I understand the need for it thought =\

**Comment by thekordy** [comment]
Switched to v0.1.0 branch #34

**Comment by thekordy** [comment]
Forked new branch for this feature https://github.com/thekordy/ticketit/tree/v0.1.0-closing_tickets

**Pull request closed without merging**
