### PR TITLE
Add DataTables. 

### PR DESCRIPTION
**Pull request by FusionDesign**
* Laravel Datatables added as dependency
* Switch all methods to Datatables.
* Rewrite Agent List method to address main branch issue. Incorrect 5.1 usage (missing ->all() to return empty array, no need for ->toArray() or checks)

### CODE REVIEW

**Comment by FusionDesign** [comment]
Working on fixing search.

**Comment by FusionDesign** [comment]
All tables are now dynamically generated by Datatables per permission level, search is working. Complete tickets does not work anymore. I have no idea how to fix it, as I can't figure out why the $ticket->status->id is not coming through on the TicketitServiceProvider line 50.

**Comment by FusionDesign** [comment]
Pagination from config has updated values.

**Comment by FusionDesign** [comment]
Bug: TicketitServiceProvider Updating:: method is not closing tickets on my end. Let me know if you experience this too. Should be an easy fix but I can't understand it.

**Comment by FusionDesign** [comment]
[Imgur](http://i.imgur.com/rJQHwmF.png)

**Comment by thekordy** [comment]
@FusionDesign  What a magnificent work here :+1:  .. I am working on many conflicts because of some commits differences, I will try to finish it tonight, but we may need to release the v0.1.0 as it's now and to start v0.2.0 (listing, filtering, searching) with the datatables you have done here, that will give as more time to test and develop.

What do you think about that?

**Comment by thekordy** [comment]
Finally, I resolved all conflicts issues and now v0.2.0 is up-to-date https://github.com/thekordy/ticketit/tree/v0.2.0

**Comment by FusionDesign** [comment]
I love that idea, thanks for the feedback. It was fun creating it and 
giving it a fresh look!

**Pull request closed without merging**
