### PR TITLE
update for laravel 5.4

### PR DESCRIPTION
**Pull request by brazitech**
update as per closed pull request

### CODE REVIEW

**Review by codercotton — APPROVED** [review]
Looks good, please approve the PR!

**Comment by codercotton** [comment]
How long will this take to get into composer?  Next release I suppose?

**Comment by thekordy** [comment]
```
composer require kordy/ticketit:0.2.x-dev
```

**Comment by thekordy** [comment]
Kindly let us if this solved your problem.

**Comment by codercotton** [comment]
It did fix my install issue - thanks a lot!

**Comment by brazitech** [comment]
worked like a charm....problem solved..
Thank you 
:-) 👍

**Pull request merged**
