### PR TITLE
Using tkTrans() helper function to reach more compact and DRY code

### PR DESCRIPTION
**Pull request by imanghafoori1**

### CODE REVIEW

**Comment by balping** [comment]
:-1: 

I don't see why this is good. This doesn't make the code DRYer, just hides some prefixes, or rather renames prefixes, eg.:  `trans('ticketit::admin.'` => `tkAdminTrans`. So it doesn't remove duplicated code, just shortens things (a little bit) and makes things counter-intuitive.

**Comment by imanghafoori1** [comment]
I know somehow it is a matter of taste...
But magic strings are better to be centerlized.
Less Typos will happen... and code gets more concise.
Also it is easier to change those strings in future.

**Comment by imanghafoori1** [comment]
All and all, these helper functions are an internal API for this package.

**Comment by imanghafoori1** [comment]
@balping 
Are agree to use the laravel-widgetize package for refactoring and caching?

**Comment by balping** [comment]
Is that package backwards-compatible until 5.1?

**Comment by imanghafoori1** [comment]
Yes

**Comment by balping** [comment]
Good. Maybe we give it a try :-)

**Pull request closed without merging**
