### PR TITLE
hungarian translation updateted

### PR DESCRIPTION
**Pull request by balping**
This package has improved a lot since I last was here. Congrats guys :-)

### CODE REVIEW

**Comment by thekordy** [comment]
Thank you, it would not really reached this point without your help and the great contribution as well from the other heroes @FusionDesign and @fishmad :)

**Comment by thekordy** [comment]
@balping  Is it possible to solve the merge conflict?

**Comment by balping** [comment]
I dont really understand why is there a merge conflict, I think the easiest
way is if you just copy my two modified files to your own repo and then
make a commit. But if you'd like to, I can try making another pull request

**Comment by thekordy** [comment]
Done :+1:

**Pull request merged**
