### PR TITLE
Proposal: Email templates

### PR DESCRIPTION
**Pull request by fusiondesign**
:)

ticketit-dashboard

ticketit-new-emails

### CODE REVIEW

**Comment by fusiondesign** [comment]
The template is extensible further through the config with some more tweaks

**Comment by fusiondesign** [comment]
I'm really pushing for that shirt haha

**Comment by fusiondesign** [comment]
I'll add more variables to config for colors if you like it. lemme know

**Comment by fishmad** [comment]
Looking great Brian, I was also leaning towards storing the email context in a database table, and create a user interface in the admin area so email template content can be edit (one for each of the different email notification type) and can have useable tags such as :name :subject :body :agent :category and so on. than the user can drag tags around to customize layout.

Need an admin interface for editing emails.

**Comment by fishmad** [comment]
Just a thought;
Possibly move these values into localization email lang:

```
'email' => [  
    'header'           => trans('ticketit::email./globals.ticket_updated'), // thoughts?  
    'signoff'          => 'Thank you for your patience!',  
    'signature'        => 'Your friends',  
    'dashboard'        => 'My Dashboard',  
    'footer'           => 'Powered by Ticketit',  // trans('ticketit::lang.globals.powered_by), 
    'footer_link'      => 'https://github.com/thekordy/ticketit',  // trans('ticketit::lang.globals.powered_by_href), 
```

Also in reference to the social links, can you set a flag that if a user may not want to use them:

`// Default = #, http://linkto,  or  'false' to disable link and icons in email`
`'google_plus_link' => false,  // I may not have or want to display google+`
`'facebook_link'    => '#',`
`'twitter_link'     => '#',`

`// in email template:`
`if google_plus_link not == false {`
    `show it...'
`}`

**Comment by thekordy** [comment]
@FusionDesign  Wow Brian .. That's awesome :+1: 

Let's discuss @fishmad points and then merge it! Good work Brian :100:

**Comment by fusiondesign** [comment]
Thanks! I'm actually working on refactoring now! Welcome back, hope ya slept well haha

**Comment by thekordy** [comment]
@FusionDesign  We couldn't convince Adam my 2 years son that he should sleep early, so I've got only 4 hours sleep .. fair enough  :)

**Comment by fusiondesign** [comment]
@thekordy haha good stuff. That's how I am. My sleep schedule is so odd.

**Comment by fusiondesign** [comment]
I have a slight problem. Cannot use trans() in config file, because it boots before the app does I guess.. not sure what to do here since it should be configurable by user and not hidden in our lang files

**Comment by fishmad** [comment]
Doing dinner for kids, let me think about for a bit and get back to you.

**Comment by fishmad** [comment]
The style settings and any configurations can stay in config but I think all languages should be in one location, I'm thinking long term and big picture here with a languages crud system and cache file like you suggested in another post.

Trying to avoid doing too much refactoring in the future.

**Comment by fusiondesign** [comment]
I'm grabbing an energy drink from the gas station. I'll be back to get to work on a migration to table-based cached results.

**Comment by fusiondesign** [comment]
Just prepping my template further before heading out so I don't have to mess with it too much once I incorporate configurable database caching lifetime.

**Comment by fusiondesign** [comment]
I'd like to merge this PR, because I have something special for you guys. Check this out:

settings_table

The database automatically checks upon seeding if a value already exists. If it does, it just updates the default automatically. If it doesn't, it loads it from a pre-defined config that we are already using.

Essentially I re-created your config-merger with a database setup.

**Comment by fusiondesign** [comment]
All you do is run: php artisan db:seed --class=Kordy\Ticketit\Seeds\SettingsTableSeeder

**Comment by fusiondesign** [comment]
Here it is if you'd like to see how I've done it:

http://laravel.io/bin/Yy4vR

**Comment by fusiondesign** [comment]
No user settings will ever be touched and defaults will always be readily available if the user messes something up! I'm excited about this one.

**Comment by fusiondesign** [comment]
@fishmad the lang is an override for the "value" field if you would like to localize a result.

**Comment by fusiondesign** [comment]
$table->string('lang')->unique();
$table->string('slug')->unique();
- Both unique so nothing collides

**Comment by fishmad** [comment]
man thats nice, I cant wait for the merge so I can have play.

think i'll hold out for @thekordy to merge so I don't mess anything up.

**Comment by fusiondesign** [comment]
Oh for sure, It's not even project-wide implemented yet. I didn't want to get too far into it this morning because I'm falling asleep at my keyboard.

**Comment by fishmad** [comment]
haha, I stayed up to 4am the other night doing localizations then up again at 8am and back into it.

Love the fact that you guys are based somewhere else in the world and in different timezones it means production advances right around the clock, every time I check this project on github there's something bigger and better everyday.

I'm still trying to figure out how to merge the commits from here to my fork, I've been deleting my fork and recreating it every time you guys merge pull requests so I don't get to far behind with my commits.

**Comment by fusiondesign** [comment]
I can show ya!

git fetch thekordy // Fetches all of thekordy's branches

git branch -v // Shows all of your current local branches.

git checkout fusiondesign v0.1.0 // Switches to my old branch

git reset --hard fusiondesign/v0.1.0 // If I switched computers recently, I need to get the latest version to delete the branch.

git checkout 0.1 // Switch to the new branch

git branch -d v0.1.0 // Deletes the branch from my machine.

git push fusiondesign :v0.1.0 // Push the branch up to Github and tell them to delete it.

git reset --hard thekordy/0.1 // Tell the directory to grab the newest version of the 0.1 branch

git add -A // Adds all files from this branch to a local commit

git push fusiondesign 0.1 // Send it up to Github

Rinse and repeat for each branch. I suggest making a bash or batch file depending on your OS to automate this.

**Comment by fusiondesign** [comment]
I know I love it too. Every single time I wake up, tons of new replies and discussion.

**Comment by fusiondesign** [comment]
Oh I name all my remote branches after github.

So to make those commands work you need to:

git remote -v // List remote repos (thekordy, fusiondesign, fishmad)

git remote add thekordy :github .git link // Add a repo

git remote rm thekordy // Remove a repo

**Comment by fishmad** [comment]
Are you using GitHub Desktop or something else?

**Comment by fusiondesign** [comment]
Nah I'm on Linux Mint 17.2 but I'm nearly asleep I can't do much more haha. I use all custom scripts so I just type "s t" and it synces all my branches with Kordy's

**Comment by fishmad** [comment]
Were have you defined the email width?

capture

**Comment by thekordy** [comment]
There so much energy here and I can barley follow up with you :) 
and sorry guys, I couldn't follow up today because of some troubles with my home internet connection (and it is not yet fixed).

To test Pull Requests locally (and you can push it to your repository) , I follow this guide:
https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by thekordy** [comment]
> All you do is run: php artisan db:seed --class=Kordy\Ticketit\Seeds\SettingsTableSeeder

I do not mind, but I'd like to find out first if there is an alternative solution which does not need another command from users, making it easier for users to upgrade. 

I was thinking of something like a function

``` php
if (File::isFile('../config/ticketit.php')) {
    $user_configs = include('../config/ticketit.php')
    File::move('../config/ticketit.php', '../config/ticketit.php.backup')
```

fetch $user_configs one way or another to the database .. I didn't try this method .. it's just something came to my mind and I liked to share

**Comment by fishmad** [comment]
Thanks @thekordy, I cant believe I never noticed that link at bottom of pull request before.

my bad. cached view error
php artisan view:clear

**Comment by thekordy** [comment]
Ok, I will proceed then with the merge

**Comment by fusiondesign** [comment]
I'll be working on the new database config merge that you requested tonight thekordy :)

**Pull request merged**
