### PR TITLE
Ticketit with places

### PR DESCRIPTION
**Pull request by Eaglemcz**
Updated and uploaded files for the "places" table

### CODE REVIEW

**Comment by Eaglemcz** [comment]
i have a litle issue for editing tickets:
it do not retrieve place's color to show the colorful place name, that's what i am working around.

After that, i tried to insert places to dashboard, but i was not able at this moment. But it will be necessary once we have place's tickets to meassure.

**Comment by balping** [comment]
Still too many files included, but never mind, I'll try to handle it manually. But not now, as i'm leaving for holiday. I'll get back to this in 7-10 days.

**Comment by Eaglemcz** [comment]
Do i have to do some coding to solve the files conflict at this branch, if yes, let me know.

**Comment by balping** [comment]
That would be great! Sorry, for having this open for this long, besides my studies I have very limited time to maintain this project.

**Comment by Eaglemcz** [comment]
Hi there, i´ve made some updates in dashboard viewing for places pizza counter. just waiting for the integration merge, to add the features. Regards!

**Comment by thekordy** [comment]
I think this is an installation of Laravel, this can't be merged to ticketit package.

**Pull request closed without merging**
