### PR TITLE
Update nav.blade.php

### PR DESCRIPTION
**Pull request by andylord56**
links more friendly to users

### CODE REVIEW

**Comment by thekordy** [comment]
This is fixed, we need to get the configured routes from settings

**Comment by andylord56** [comment]
Can you please show this in the documentation how to change this as I could not find how to do this yesterday and resulting in me changing the nav to this.

**Comment by thekordy** [comment]
Sure, You will need to login with an administrator account or with the user account with id 1 and go to `Settings->configuration->Initial`

configure `main_route` for the users front-end path
configure `admin_route` for the back-end path

in the latest version (will be released soon or just update your local ticketit repository)
configure `main_route_path` for the users front-end path
configure `admin_route_path` for the back-end path

laravel - helpdesk main page 2016-03-05 13-09-20

laravel - configuration settings 2016-03-05 13-11-27

**Comment by andylord56** [comment]
We would need an explanation on how to do it via database as we wouldnt be able to get to this as links are broken at that time

**Comment by thekordy** [comment]
They shouldn't be broken, try to reinstall on fresh database with latest code.

**Comment by andylord56** [comment]
please see #162 for more information on what happened when i installed

**Comment by thekordy** [comment]
Yes, I saw it. You need to make fresh installation with fresh database and with the latest code, and just make sure to have [jquery and master template integration are done right](https://github.com/thekordy/ticketit/wiki/Integrating-Ticketit-views-with-your-project-template)

**Comment by andylord56** [comment]
this was a fresh new laravel install fresh database i used for testing before moving onto my main laravel site, i had jquery and template integration done right near the end of the issue but yet the links was still a problem, if i had the jquery and template integration done correctly before install would the links of worked is this what your saying if so ill test this ?

**Comment by thekordy** [comment]
yes

**Comment by andylord56** [comment]
something that could possibly fix this is to have a general template file that they could select and edit later on rather then creating one themselves as i see it can cause a lot of installation problems also updating the wiki, i have tested this and can confirm with the correct Jquery and template in place it works fine. without Jquery it will not work at all.

**Comment by thekordy** [comment]
Yes, that would very helpful, I will see what I can do about that.

**Pull request closed without merging**
