### PR TITLE
Fixed error yajra datatables in Laravel 5.4

### PR DESCRIPTION
**Pull request by xdnan7**
Fixed error class Datatables not exist and DataTablesServiceProvider not found in Laravel 5.4.

### CODE REVIEW

**Comment by balping** [comment]
5.4 should be compatible with 8.0. What error message do you get otherwise?

https://github.com/yajra/laravel-datatables#laravel-version-compatibility

**Comment by xdnan7** [comment]
The version Yajra Datatables in laravel 5.4 was 6.x not 8.x. So I've added 7.0, to have composer got the version 7.x instead.

**Comment by balping** [comment]
Just tried a fresh install and 8.* is installed for me. Something else must be in conflict with 8.* for you.

```
$ composer create-project laravel/laravel test 5.4.*
Installing laravel/laravel (v5.4.30)
  - Installing laravel/laravel (v5.4.30): Downloading (100%)         
Created project in test
...

$ cd test
$ composer require 'kordy/ticketit:0.*'
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 12 installs, 0 updates, 0 removals
  ... 
  - Installing yajra/laravel-datatables-oracle (v8.6.0): Downloading (connectingDownloading (100%)         
  - Installing kordy/ticketit (v0.3.13): Downloading (100%)         
  ...
```

**Comment by xdnan7** [comment]
Thanks for your feedback balping..
sorry forgot to mention, i use your quick installer ticketit-app..
Maybe something conflict in quick installer.

**Comment by balping** [comment]
Again, it installs 8.6 for me:

```
$ composer create-project balping/ticketit-app test 1.0.8
Installing balping/ticketit-app (v1.0.8)
  - Installing balping/ticketit-app (v1.0.8): Downloading (100%)         
Created project in test
> php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 73 installs, 0 updates, 0 removals
  - Installing laravel/framework (v5.4.36): Loading from cache
  - Installing yajra/laravel-datatables-oracle (v8.6.0): Loading from cache
  - Installing kordy/ticketit (v0.3.13): Loading from cache
```

yajra/laravel-datatables-oracle requires php 7. Maybe your php version is too old?

**Comment by xdnan7** [comment]
Thanks balping, yes you're right, my php version is 5.6.

**Pull request closed without merging**
