### PR TITLE
accept new comments and tickets through email

### PR DESCRIPTION
**Pull request by tmcdon89**
Some notes:
I wasn’t able to get the email attachments going through the validator
class, so its currently doing a regex check on the extension type
rather than checking against the mime the way the uploaded attachments
do.

I need some help getting the agent auto assignment working with newly
created email tickets. I haven’t had time to get into the issue to make
it work, so currently the “default_email_agent” needs to be an agent
and not “auto”

It would probably be better if the “imap_password” setting was hashed
like a password should be but thats beyond me at the moment.

### CODE REVIEW

**Comment by thekordy** [comment]
What a wonderful work you have done here :clap:  ..  I will test and add the auto assignment as soon as I get to home tonight.

If you are not working on that already, I am also thinking about creating new accounts on the fly for the unregistered emails or to find a way to give them a guest temporary pass to their created tickets. What do you think?

**Comment by tmcdon89** [comment]
I think an option to allow auto creation of accounts would be awesome. Especially if it were additionally able to be limited by domain addresses. So:
1 ) do nothing with unknown accounts 
2 ) create new accounts for unknown emails
3 ) create new accounts only for emails with domains @123.com and @abc.com etc....
Guest temporary passes would also be nice but perhaps harder to accomplish?

as always thanks for the input and help!

**Comment by thekordy** [comment]
I could get it to work .. I installed the php-imap package and made the required configuration but I get this error

``` php
Exception in Mailbox.php line 67: Connection error: [CLOSED] IMAP connection broken (server response)
```

I can login to imap and get the inbox emails using php imap_open on a side script, but can not get it work when I press the get email button.

**Comment by balping** [comment]
Wow, great! Soon this package will become a full-functional issue manager

**Comment by tmcdon89** [comment]
@thekordy What debugging have you tried so far? I haven't run into that issue in particular. What type of server are you connecting to? gmail, office365, yahoo etc...?  If its not the same computer/server that the side script is running on is it possible that gmail server or similar is blocking the connection as unknown app? I've had this happen before when connecting email applications.

I'm making the assumption you're using the same settings in your side script thats working?
My first thought would be to put in a var dump of the $mailbox to make sure all of the settings are being applied correctly.

**Comment by tmcdon89** [comment]
Oops sorry for all the merge and reverts! I was checking something and didn't realize I was committing those.

**Comment by thekordy** [comment]
@balping I hope so .. Thank you, you helped a lot to get the package to this point :)

**Comment by thekordy** [comment]
@tmcdon89 It worked on my work machine, it might be my fault last night. and I am using gmail. 

Great work indeed, and here are some points from my trial:

It's opening new tickets successfully if found any new emails
It successfully moves them to the archive email folder 
It does not add the reply email as a comment to the original ticket, instead it creates a new ticket for the reply email

email tickets

It could not download and attach the email attachment
It could not filter out the signature 

email reply ticket with attachment

**Comment by thekordy** [comment]
Hi @tmcdon89 ... Can I have your email address? If that is OK with you. My email is ahmed@kordy.info

**Comment by tmcdon89** [comment]
Sure @thekordy it's tom@aerowavenetworks.com

**Comment by kasirye** [comment]
@thekordy am get the same error. can you teach me on what you did to get it to work...
Slug                      Default Value                     My Value
imap_server     imap.gmail.com:993/imap/s...    imap.gmail.com:993/imap/s...  
imap_folder     Inbox                                           Inbox  
imap_user   mymail@gmail.com                    xxxxxxx@gmail.com  
imap_password   mypassword                          mypassword      

default_outgoing_email  user                            mymail@gmail.com  
default_outgoing_name   user                            user  
default_emails_agent    auto                            auto  
move_email_to   

How do i fill in these settings to make the emails functionality work. Am i making a mistake. Please help

**Comment by kasirye** [comment]
It has pulled all attachments but no emails

**Comment by tmcdon89** [comment]
If you use developer tools on chrome or firebug on firedox are you able to see any errors after activating the "get emails" button?

**Comment by kasirye** [comment]
let me try that

**Comment by kasirye** [comment]
Funny i dont see any errors ... though i get this from the page after i click getmails

 FatalErrorException in Mailbox.php line 54: Maximum execution time of 60 seconds exceeded

and i get alot of images and docs in the app/attachment directory

**Comment by tmcdon89** [comment]
How many emails are in the folder you are parsing through?

**Comment by kasirye** [comment]
about 10

**Comment by tmcdon89** [comment]
Just to check since its a timeout error. If you reduce it to 1-2 emails does it work?

**Pull request merged**
