### PR TITLE
Add validation!

### PR DESCRIPTION
**Pull request by FusionDesign**
Adds validation via Form Requests, start to fix bootstrap modal width for Categories or Statuses that extend past given area. Will update demo with shorter categories until I find an elegant solution. Also updates a few controller methods that were crippled by lack of form request.

### CODE REVIEW

**Comment by FusionDesign** [comment]
If you prefer, I can bundle the request into the package, without having to publish them. I just was thinking about custom fields for per-user needs.

**Comment by FusionDesign** [comment]
Also, I'm on linux so that's why you have odd file mode changes.

**Comment by FusionDesign** [comment]
I finally got around to learning how to use umask on linux after repeating chmod/chown for years. So I patched up that file mode problem.

**Comment by thekordy** [comment]
Well done :100: 

But I was thinking, What if we wanted to update published files, then we need to do the [publish command automatically](http://laravel.com/docs/5.1/packages#public-assets), and that would override user changes :)
I don't see any wrong of publishing requests files, but making it auto published would be mandatory, so finding another way to allow custom fields would be better, like doing it through database and admin panel, or config file, something like that.

What do you think?

**Comment by FusionDesign** [comment]
Yeah I agree. Lets try to make it flexible, to a point. We want the package to still be upgrade-able. I'm going to push a few more changes and see what you think.

**Comment by FusionDesign** [comment]
I'm going to save some time tonight to rethink some things. Gotta work on the home site for a bit to track errors.

**Comment by thekordy** [comment]
Thank you for the validation feature, now for the first time i can say the package has grown and became ready for production use :)

**Comment by FusionDesign** [comment]
Aww thanks! I'll be here for a while. I'm growing my company while you grow your package.

**Pull request merged**
